server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    root: info

---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: prod